name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - uses: dominikh/staticcheck-action@v1.1.0
      with:
        install-go: false

    - name: Check Format
      run: make check

    - name: Build
      run: make build-default

    - name: Test
      run: make test
